Parameters:
  EnvironmentName:
    Type: String
    Default: CovidDataLoader
Resources:
  DDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "date"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "date"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: "covidData"
  WriteCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 15
      MinCapacity: 5
      ResourceId: !Join
        - /
        - - table
          - !Ref DDBTable
      RoleARN: !GetAtt ScalingRole.Arn
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      ServiceNamespace: dynamodb
  ScalingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - application-autoscaling.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "dynamodb:DescribeTable"
                  - "dynamodb:UpdateTable"
                  - "cloudwatch:PutMetricAlarm"
                  - "cloudwatch:DescribeAlarms"
                  - "cloudwatch:GetMetricStatistics"
                  - "cloudwatch:SetAlarmState"
                  - "cloudwatch:DeleteAlarms"
                Resource: "*"
  WriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: WriteAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref WriteCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 50.0
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "SNSTopic-${AWS::StackName}"
  covidSNSpolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
         -
           Action: "sns:Publish"
           Effect: Allow
           Principal:
             AWS: "*"
           Resource:
             Ref: SNSTopic
      Topics:
       -
         Ref: SNSTopic
  CovidDataLoadFunction:
    Type: AWS::Lambda::Function
    Properties: 
      Code: 
        S3Bucket:
          Fn::ImportValue: !Sub ${EnvironmentName}:coreinf-functionbucket
        S3Key: 'CovidDataFunction.zip'
      Description: 'Function to perform ETL operations on Covid Data'
      FunctionName: 'CovidDataLoader'
      Handler: 'covid-data-etl.event_handler'
      MemorySize: 256
      ReservedConcurrentExecutions: 1
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: 'python3.6'
      Timeout: 240
      TracingConfig:
        Mode: Active
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${EnvironmentName}:NoIngressSecurityGroup
        SubnetIds:
          - Fn::ImportValue: !Sub ${EnvironmentName}:PrivateSubnet1
          - Fn::ImportValue: !Sub ${EnvironmentName}:PrivateSubnet2
      Environment:
        Variables:
          LOGGER_LEVEL: INFO
          JOHN_HOPKINS_DATA_URL: https://raw.githubusercontent.com/datasets/covid-19/master/data/time-series-19-covid-combined.csv?opt_id=oeu1601336451462r0.5279466816848477
          USA_COVID_DATA_URL: https://raw.githubusercontent.com/nytimes/covid-19-data/master/us.csv
          SNS_TOPIC: arn:aws:sns:ap-southeast-2:955966247963:SNSTopic-core-infrastructure-covid-app
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - dynamodb:PutItem
            - dynamodb:DescribeTable
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:UpdateItem
            Resource: arn:aws:dynamodb:ap-southeast-2:955966247963:table/covidData
          - Effect: Allow
            Action:
            - ec2:DescribeNetworkInterfaces
            - ec2:CreateNetworkInterface
            - ec2:DeleteNetworkInterface
            - ec2:DescribeInstances
            - ec2:AttachNetworkInterface
            Resource: '*'
          - Effect: Allow
            Action:
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
            Resource: '*'
  ScheduledRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "ScheduledRule"
      ScheduleExpression: "cron(0 9 * * ? *)"
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "CovidDataLoadFunction"
              - "Arn"
          Id: "TargetFunctionV1"
  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: "CovidDataLoadFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "ScheduledRule"
          - "Arn"
Outputs:
  SNSTopic:
    Description: SNSTopic for alerts
    Value: !Ref SNSTopic
    Export: 
      Name: !Sub ${EnvironmentName}:SNSTopic
  CovidDataLoadFunction:
    Description: Lambda function that loads the COVID data into DynamoDB
    Value: !Ref CovidDataLoadFunction
    Export: 
      Name: !Sub ${EnvironmentName}:CovidDataLoadFunction