Parameters:
  ApiName:
    Type: String
    Default: CovidDataApi
    Description: "creation of api"
  EnvironmentName:
    Type: String
    Default: CovidDataLoader
  PathPart:
    Type: String
    Default: cumulativedata
Resources:
  APIGatewayCovidDataServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "dynamodb:Scan"
                Resource: "arn:aws:dynamodb:ap-southeast-2:955966247963:table/covidData"
  CovidDataApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties: 
      Name: !Ref ApiName
  CovidDataResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      RestApiId:
        Ref: CovidDataApi
      ParentId:
        Fn::GetAtt:
          - CovidDataApi
          - RootResourceId
      PathPart: 
        Ref: PathPart
  CovidDataGet:
    DependsOn: CovidDataApi
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: 
        Ref: CovidDataApi
      ResourceId: 
        Ref: CovidDataResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Credentials: !GetAtt APIGatewayCovidDataServiceRole.Arn
        Type: AWS
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:dynamodb:action/Scan"
        RequestTemplates:
          application/json: >-
            {
                "TableName": "covidData"
            }
        IntegrationResponses:
          - ResponseTemplates:
              application/json: >-
               #set($inputRoot = $input.path('$'))
               {
                   "records": [
                       #foreach($elem in $inputRoot.Items) {
                           "date": "$elem.date.S",
                           "cases": "$elem.cases.N",
                           "deaths": "$elem.deaths.N",
                           "recovered": "$elem.recovered.N"
                       }#if($foreach.hasNext),#end
                   #end
                   ]
               }
            StatusCode: 200
      MethodResponses:
        - ResponseModels:
            application/json: Empty
          StatusCode: 200
  CovidDataApiDeploy:
    DependsOn: 
      - CovidDataApi
      - CovidDataGet
      - CovidDataResource      
    Type: "AWS::ApiGateway::Deployment"
    Properties:
      RestApiId:
        Ref: CovidDataApi
      Description: "Deployment for this CovidDataApi"
      StageName: 'live'
      
Outputs:
  CovidDataApiUrl:
    Description: Url of deployed API
    Value: !Sub "https://${CovidDataApi}.execute-api.${AWS::Region}.amazonaws.com/live/${PathPart}"
    Export: 
      Name: !Sub ${EnvironmentName}:CovidDataApiUrl